name: 生产环境部署
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
        with:
          persist-credentials: false
      
      - name: 下载依赖 打包项目
        run: 
          npm install -g pnpm@8
          pnpm install
          pnpm build
      - name: 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        env: # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.PRIVATE_KEY }}
          BRANCH: ph-pages
          FOLDER: ../../dist
          REPOSITORY_NAME: https://Fanyinqian.github.io/Focus-pro